// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRSxR2RGbywwp15WIyvb8p_cw-jtAL3Ro',
    appId: '1:787370737165:web:3beb80113cbc6d77459f44',
    messagingSenderId: '787370737165',
    projectId: 'memoa-68187',
    authDomain: 'memoa-68187.firebaseapp.com',
    databaseURL: 'https://memoa-68187-default-rtdb.firebaseio.com',
    storageBucket: 'memoa-68187.firebasestorage.app',
    measurementId: 'G-GG11KC2ZKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjLGSpCs2o14jbkA92pWH34AUfScjxsLI',
    appId: '1:787370737165:android:646822852b6fa5ae459f44',
    messagingSenderId: '787370737165',
    projectId: 'memoa-68187',
    databaseURL: 'https://memoa-68187-default-rtdb.firebaseio.com',
    storageBucket: 'memoa-68187.firebasestorage.app',
  );
}
